### ISSUE TITLE
Week of 09.01.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#119]
- [x] Logan Foundation report draft (#118)
- Playbook
  - [ ] Get club fair, 1st workshop, and 1st day guidelines on master (hackedu/hackedu#120, hackedu/hackedu#121, hackedu/hackedu#122)
    - [x] Dave's changes added
    - [x] Read over by Abe and Aaroh and any feedback added
    - [ ] At least 2 pull request from leaders
  - [ ] Pull request submitted with 2nd club meeting draft
- Community
  - By the end of the week, we want cohort 1's group chat to be the go-to place for labs
    - If Gemma hasn't posted by 6PM Wednesday, ping her to post in the group
  - [x] Start cohort 2 group chat (hackedu/hackedu#113)
    - Have Jiahao post about club fair happening by Wednesday
  - [ ] Cohort 2 group call this weekend (hackedu/hackedu#114)
  - End of week goals:
      - [ ] 3 organic posts with discussion in FB group
      - [ ] 25 introduction posts
      - [ ] 5 Medium posts

/cc @jonleung @hellyeah

**Comment by jonleung** [comment]
@zachlatta, revisions need to be made to this plan based on [this meeting](https://github.com/hackedu/hackedu/blob/be402c47456d74ffcec238910b207d3705213a85/meta/labs/meetings/15-09-03_who_writes_the_initial_playbook.md#conclusion).

I am happy to take point on this if you want!

**Comment by zachlatta** [comment]
That'd be awesome! Can you comment with a draft of how you'd change it, then I'll make the revision itself? Feel free to ping me on IRC while you're doing this.

**Comment by jonleung** [comment]
@zachlatta, actually since I picked up some new work, I'm not sure if I have the bandwidth to do this right now : /
