### ISSUE TITLE
Week of 09.07.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#126]
- [ ] Labs
  - [ ] For anyone in Labs running something this week, they have submitted
    two pull requests: one for planning, the other for post-mortem. (@hellyeah, hackedu/hackedu#169)
  - [ ] Any leaders that submit pull requests have shared with their Labs
    cohort and received feedback (if applicable). (@hellyeah, hackedu/meta#136)
- [ ] Curriculum
  - [ ] Create workshop that enables every club member to ship a project to shipit on the first day (@jonleung, hackedu/hackedu#171)
- [ ] Shipit
  - [x] Make sure that shipit.hackedu.us includes a dropdown with every high school we have (@zachlatta, hackedu/hackedu#119)
- [ ] Meta
  - [ ] Salaries paid (@zachlatta, hackedu/meta#125)
  - [x] Mission Bit expense report for August done (@zachlatta, hackedu/finances#4)
  - [ ] Logan report done and sent in (@zachlatta, hackedu/meta#118)
    - [ ] Send it to Dave after reading through Jonathan's comments
  - [x] Defer decision pending applicants to early next week (@zachlatta, hackedu/meta#127)
  - [x] Dave reads README of https://clubs.hackedu.us (@hellyeah)
  - [ ] Dave reads https://github.com/hackedu/hackedu/blob/master/CONTRIBUTING.md#labs (@hellyeah)
- [ ] Community (@hellyeah)
  - [ ] 5 organic posts with discussion in FB group (hackedu/meta#129)
  - [ ] 10 introduction posts (hackedu/meta#129)
  - [ ] 5 Medium posts (hackedu/meta#129)
  - [ ] Check-in with every Labs leader (@hellyeah, hackedu/meta#135)

/cc @jonleung @hellyeah @MaxWofford

**Comment by MaxWofford** [comment]
Are we back to weekly sprints @zachlatta @jonleung @hellyeah @prophetorpheus ?

**Comment by zachlatta** [comment]
Of sorts. We're doing a mix of weekly sprint issues + kanban.

On Wed, Sep 9, 2015 at 2:11 AM, Max Wofford <notifications@github.com>
wrote:

> Are we back to weekly sprints @zachlatta <https://github.com/zachlatta>
> @jonleung <https://github.com/jonleung> @hellyeah
> <https://github.com/hellyeah> @prophetorpheus
> <https://github.com/prophetorpheus> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/126#issuecomment-138847994>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
End of week status:

- [ ] Labs
  - [ ] For anyone in Labs running something this week, they have submitted
    two pull requests: one for planning, the other for post-mortem. (@hellyeah,
    hackedu/hackedu#169)
    - _Status:_ Bogdan submitted one, Gemma didn't. Didn't get planning for
      either. Didn't complete this task.
  - [ ] Any leaders that submit pull requests have shared with their Labs
    cohort and received feedback (if applicable). (@hellyeah, hackedu/meta#136)
    - _Status:_ Bogdan shared, Gemma didn't. Jiahao shared. Didn't complete this
      task.
- [ ] Curriculum
  - [ ] Create workshop that enables every club member to ship a project to
    shipit on the first day (@jonleung, hackedu/hackedu#171)
    - _Status:_ Sitting on a branch, no pull request submitted. Didn't complete
      this task.
- [x] Shipit
  - [x] Make sure that shipit.hackedu.us includes a dropdown with every high
    school we have (@zachlatta, hackedu/hackedu#119)
    - _Status:_ Done.
- [ ] Meta
  - [ ] Salaries paid (@zachlatta, hackedu/meta#125)
      - _Status:_ Just got Dave's address, going to get that out ASAP.
  - [x] Mission Bit expense report for August done (@zachlatta,
    hackedu/finances#4)
      - _Status:_ Done
  - [ ] Logan report done and sent in (@zachlatta, hackedu/meta#118)
    - [ ] Send it to Dave after reading through Jonathan's comments
    - _Status:_ Nearly done. Sending it out tonight.
  - [x] Defer decision pending applicants to early next week (@zachlatta,
    hackedu/meta#127)
      - _Status:_ Done
  - [x] Dave reads README of https://clubs.hackedu.us (@hellyeah)
      - _Status:_ Read it, gave me some feedback. Done, but not done well.
  - [ ] Dave reads
    https://github.com/hackedu/hackedu/blob/master/CONTRIBUTING.md#labs
    (@hellyeah)
      - _Status:_ Read it, gave me some feedback. Done, but not done well. No
        feedback given.
- [ ] Community (@hellyeah)
  - [x] 5 organic posts with discussion in FB group (hackedu/meta#129)
    - _Status:_ Done
  - [ ] 10 introduction posts (hackedu/meta#129)
    - _Status:_ Didn't hit it
  - [ ] 5 Medium posts (hackedu/meta#129)
    - _Status:_ Didn't hit it
  - [x] Check-in with every Labs leader (@hellyeah, hackedu/meta#135)
    - _Status:_ Done

Closing due to week being over.
