### ISSUE TITLE
Week of 09.14.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#151]
- [x] Applicants
  - [x] Get back to existing hackEDU applicants (@hellyeah, hackedu/meta#145)
- [ ] Curriculum
  - [x] Work with each club that has a meeting this week to do setup for it (@jonleung, hackedu/meta#146)
  - [x] Make sure that every club that had meetings last week submits a case study (@hellyeah, hackedu/meta#147)
  - [ ] **BLOCKING**: Make sure that every club that has meetings this week submits a case study (@jonleung, hackedu/meta#147)
  - [ ] **Waiting for merge**: Get 2nd workshop for clubs onto master (@jonleung)
  - [x] Create GitHub Issues for problems with 2nd workshop (@jonleung, hackedu/hackedu#208)
  - [ ] Create draft of the 3rd workshop (@jonleung, hackedu/hackedu#209)
  - [ ] **Waiting for merge / discussion:** Write brief suggested guidelines for project and workshop day model (@jonleung, hackedu/hackedu#210)
- [ ] Community
  - [ ] ~~Work with club leaders from this week to make sure that the meeting experience for the member is as great as physically possible (@hellyeah)~~
  - [x] Sync up with club leaders ASAP (@hellyeah, hackedu/meta#149)
    - [x] Find out which clubs have meetings this week by the end of Monday
      (@hellyeah, hackedu/meta#148)
- [x] Club Platform
  - [x] Create MVP of platform for feedback forms and attendance (@MaxWofford, hackedu/meta#150)
- [x] Meta
  - [x] Pay August salaries (@zachlatta, hackedu/meta#125)
  - [x] Send off Logan report (@zachlatta, hackedu/meta#118)

/cc @hellyeah @jonleung @MaxWofford

**Comment by jonleung** [comment]
@hellyeah, note: sign contract

**Comment by hellyeah** [comment]
@jonleung sending feedback. @hellyeah will send it out after @jonleung and @MaxWofford reviews another draft.

@MaxWofford is adding more clubs this should go out to in http://clubs.hackedu.us

**Comment by MaxWofford** [comment]
@zachlatta
 > Week of 09.14.15

Does this follow our styleguides?

**Comment by jonleung** [comment]
Closing this because we have a new weekly sprint issue.
