### ISSUE TITLE
Week of 09.21.15

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#155]
The weekly question is 
> How might we create a culture of contribution?

--------------------------------------------------------------------------------
- [ ] Packrat rails shipped (@MaxWofford, hackedu/packrat#12)
  1. [ ] Packrat dashboard is added
  2. [x] Packrat analytics page is added
  3. [x] `feedback.hackedu.us` points to Packrat
  4. [x] Club leaders having meetings this week are reminded of the feedback form
- [ ] _In Progress_: 2nd workshop guidelines created (@jonleung, hackedu/hackedu#171)
- [ ] _In Progress_: 2nd workshop created (@jonleung, hackedu/hackedu#171)
- [ ] _In Progress_: 3rd workshop created (@jonleung, hackedu/hackedu#271)
- [x] Set up Labs directors check-ins before/after club meetings (@jonleung, hackedu/hackedu#157)
- [x] Create 'Labs' calendar (@hellyeah, #156)
  - [x] Add Labs meeting times to 'Labs' calendar
- [ ] Ensure Cohort 2 call is scheduled (@hellyeah, #158)
- [x] Ensure Cohort 1 call is scheduled (@gemmabusoni, #159)
- [ ] Plan Labs update meeting (@hellyeah, #160)
- [ ] 100% coverage of Labs meeting times (@hellyeah, hackedu/meta#149)

**Comment by zachlatta** [comment]
Progress updates:

- [ ] Packrat rails shipped (@MaxWofford, hackedu/packrat#12)
  1. [X] Packrat dashboard is added
  2. [X] Packrat analytics page is added
  3. [X] `feedback.hackedu.us` points to Packrat
  4. [X] Club leaders having meetings this week are reminded of the feedback
     form
  - _Update:_ It's finished, but not shipped to club leaders. Remaining work
    moved to #173.
- [ ] _In Progress_: 2nd workshop guidelines created (@jonleung,
  hackedu/hackedu#171)
  - _Update:_ Half created. Remaining work moved to #173.
- [ ] _In Progress_: 2nd workshop created (@jonleung, hackedu/hackedu#171)
  - _Update:_ Not finished, need to fix JSBin links with new code. Remaining
    work moved to #173.
- [ ] _In Progress_: 3rd workshop created (@jonleung, hackedu/hackedu#271)
  - _Update:_ Code written, workshop not written. Remaining work moved to #173.
- [X] Set up Labs directors check-ins before/after club meetings (@jonleung,
  hackedu/hackedu#157)
  - _Update:_ Done
- [X] Create 'Labs' calendar (@hellyeah, #156)
  - [X] Add Labs meeting times to 'Labs' calendar
  - _Update:_ Done
- [ ] Ensure Cohort 2 call is scheduled (@hellyeah, #158)
  - _Update:_ Did not happen. Do again this week. Remaining work moved to #173.
- [X] Ensure Cohort 1 call is scheduled (@gemmabusoni, #159)
  - _Update:_ Happened yesterday.
- [X] Plan Labs update meeting (@hellyeah, #160)
  - _Update:_ Done
- [ ] 100% coverage of Labs meeting times (@hellyeah, hackedu/meta#149)
  - _Update:_ Everyone's times are set except for those that aren't finalized
    yet. Push for this week, however this has not been moved to #173.
