### ISSUE TITLE
Create 'Labs' calendar 

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#156]
This issue can be closed once the following has been completed:

- [x] The Labs calendar has been shared with team@hackedu.us

The following issues depend on this one:

- [ ] All Labs clubs meeting times are added as events (#149)
- [ ] Cohort 1 call is scheduled (#159)
- [ ] Cohort 2 call is scheduled (#158)
- [ ] Labs director check-ins before/after meeting scheduled (#157)

**Comment by hellyeah** [comment]
@MaxWofford I'm not certain we want to have a rigid schedule for "Labs director check-ins before/after meeting scheduled (#157)"

Additionally, I don't believe the Cohort 1 (#159) and Cohort 2 (#158) calls will be scheduled rigidly so I don't think they should block this issue. 

I want to close this issue with a weekly event to get the day of the week/time from the clubs we don't have them for and a weekly event to make sure the cohort calls get scheduled. Thoughts?
