### ISSUE TITLE
Week of 09.28.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#173]
- [ ] Curriculum
  - [x] 2nd workshop guidelines created (@jonleung, hackedu/hackedu#171)
  - [x] 2nd workshop created (@jonleung, hackedu/hackedu#171)
  - [ ] 3rd workshop created (@jonleung, hackedu/hackedu#271)
  - [x] Record workshops being run by each Labs club this week (@jonleung, hackedu/meta#175)
- [ ] Community
  - [ ] Build system for automating community metrics (@hellyeah,
  hackedu/hackedu#258)
  - [x] Ensure Cohort 1 call is scheduled (@gemmabusoni, hackedu/meta#162)
  - [x] Ensure Cohort 2 call is scheduled (@gemmabusoni, hackedu/meta#158)
- [ ] Technical
  - [x] Markcop shipped (@MaxWofford, hackedu/meta#163)
  - [ ] All clubs meeting this week should use Packrat (@MaxWofford,
  hackedu/meta#164)
  - [ ] Packrat full MVP (@zachlatta)
    - [ ] Track projects from each meeting (hackedu/packrat#30) (@MaxWofford)
    - [ ] Add percentage of people that submitted projects to each meeting
      (@zachlatta, hackedu/packrat#32)
- [ ] Misc
  - [x] Schedule time to talk about switching to Slack (@zachlatta, hackedu/meta#165)
  - [x] Set time to discuss PR workflow (@MaxWofford (moved from @zachlatta), hackedu/meta#166)
  - [x] Assign people to run standups for each day this week (@zachlatta,
  hackedu/meta#168)
  - [x] Communicate standup expectations to everyone on the team (@zachlatta,
  hackedu/meta#167)
  - [x] Create new sheet in https://clubs.hackedu.us for tracking club meetings
  (@zachlatta, hackedu/meta#169)
  - [ ] Every club meeting this week should be recorded in the new sheet in
  https://clubs.hackedu.us (@hellyeah, hackedu/meta#170)
  - [ ] Talk HackingEDU with Selynna and Sam (@gemmabusoni, hackedu/meta#172)
  - [x] Set planning meeting to set objectives for the whole semester (@zachlatta,
  hackedu/meta#171)
  - [ ] Gemma pairs with Bogdan on planning and recap (@gemmabusoni,
  hackedu/hackedu#272)

/cc @jonleung @MaxWofford @hellyeah @gemmabusoni

**Comment by zachlatta** [comment]
Closing because the week is over. New weekly issue in #197.
