### ISSUE TITLE
Week of 10.05.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#197]
#### Curriculum

- [x] Ship 3rd Workshop (@jonleung, hackedu/hackedu#271)
- [ ] Ship 4th Workshop (@jonleung, hackedu/hackedu#299)
- [ ] Sync up with club leaders and add their planned curriculum for the week to
  the Meetings spreadsheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#192)

#### Community

- [x] Launch Slack (@hellyeah, hackedu/meta#193)
- [ ] Build system for automating community metrics (@hellyeah, hackedu/meta#194)
- [x] Add meetings from this and last week to https://clubs.hackedu.us
  (@hellyeah, hackedu/meta#195)
- [ ] Feedback from at least 2 clubs has been submitted using Packrat (@hellyeah,
  hackedu/meta#196)
  - [x] Get Dave access to Packrat (@zachlatta, hackedu/meta#181)

#### Technical

- [x] Ship Packrat (@zachlatta, hackedu/packrat#12)
  - [x] Add field for members to describe what they did in the meeting
    (@zachlatta, hackedu/packrat#47)
  - [x] Fix scrolling down (@zachlatta, hackedu/packrat#50)
  - [x] Refactor User model (@zachlatta, hackedu/packrat#51)
  - [x] Club Leader GitHub login (@zachlatta, hackedu/packrat#9)

#### Misc

- [x] Assign people to standups for the week (@zachlatta, hackedu/meta#182)
- [x] Schedule retrospectives and kudos sessions (@zachlatta, hackedu/meta#183)
- [ ] YC Application (make sure to show others the application) (@zachlatta,
  hackedu/meta#184)
- [ ] Pay salaries (@zachlatta, hackedu/meta#185)
- [x] Set team lunch for Wednesday (10.07.15) (@zachlatta, hackedu/meta#186)
- [x] Set weekly team lunch for Monday (@zachlatta, hackedu/meta#187)
- [x] Plan to discuss whether we should have next week's planning meeting in
  person during this week's retrospective (@zachlatta, hackedu/meta#188)
- [x] Plan time to talk about visually distinguishing weeks in the Meetings
  spreadsheet on IRC (@zachlatta, hackedu/meta#189)
- [x] Plan time tomorrow to show Packrat to Dave over IRC (invite Jonathan to
  the calendar event as well) (@zachlatta, hackedu/meta#190)
- [ ] ~~Install Steward plugin to record meeting logs (@zachlatta,
  hackedu/meta#191)~~

/cc @hellyeah @jonleung

**Comment by zachlatta** [comment]
Closing because week is over. This week's issue is in #215.
