### ISSUE TITLE
Week of 10.12.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#215]
### Curriculum

- [x] Ship 4th workshop (@jonleung, hackedu/hackedu#299)
- [x] Clean up Meetings sheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#210)
- [x] Check in with club leaders and add their planned curriculum for this week
  (10.12) to the Meetings sheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#192)
- [x] Check in with club leaders and add their planned curriculum for _last_
  week (10.05) to the Meetings sheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#211)
- [ ] Link workshop-specific feedback forms at the end of every workshop
  (@MaxWofford, hackedu/hackedu#338)
- **Backlog**
  - [ ] Ship another p5 workshop (@jonleung, hackedu/hackedu#339)
  - [x] _(Update: 2 calls completed so far)_ Check in with club leaders to get feedback on hackEDU as a whole
    (@jonleung, hackedu/meta#212)

### Community

- [x] Keep momentum going on Slack (@hellyeah, hackedu/meta#206)
- [ ] Build system for automating community metrics (@hellyeah,
  hackedu/hackedu#258)
- [ ] 3 clubs using packrat (@hellyeah, hackedu/meta#207)
- [x] Add meetings from this week to https://clubs.hackedu.us (@hellyeah,
  hackedu/meta#208)
- [x] Message Bay Area Labs leaders about HackingEDU (@jonleung,
  hackedu/meta#177)
- [x] plan to do the transition from Teagan to Jeremy (@hellyeah,
  hackedu/meta#213)

### Technical

- [x] Add user analytics to Packrat (@zachlatta, hackedu/packrat#1)
- [ ] Refactor Markcop into individual checks (@MaxWofford, hackedu/markcop#13)
  - Headers
    - [ ] Newlines before and after (hackedu/markcop#12)
    - [ ] Proper formatting
  - Link checking
  - Only ASCII chars allowed
  - [ ] Line length should be less than 80 chars (hackedu/markcop#11)
  - Trailing spaces
  - Single spaced words
- [x] Setup proxy to bypass school networks in Twilio workshop (@zachlatta,
  hackedu/hackedu#346)
- [ ] Slack <> IRC connection (@MaxWofford, hackedu/meta#209)

### Misc

- [x] YC application (includes video) (@zachlatta, hackedu/meta#184)
- [ ] Check in pairing a club leader w/ gemma (@MaxWofford, hackedu/hackedu#340)
- [ ] ~~Plan meeting to talk about Slack and IRC and how we're going to use them
  (@zachlatta, hackedu/meta#214)~~ (do next week)

/cc @hellyeah @jonleung @MaxWofford

**Comment by jonleung** [comment]
Closing this issue because we have a new weekly issue now.

**Comment by zachlatta** [comment]
New weekly issue is in #232.
