### ISSUE TITLE
Make sure everyone reads the Kanban Roadmap

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#228]
- [x] Dave reads Kanban Roadmap PDF #227
- [x] Max reads Kanban Roadmap PDF #226 
- [ ] Zach reads Kanban Roadmap PDF #225

Here is the link to [Kanban Roadmap](http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf).

**Comment by jonleung** [comment]
I am closing this issue because it has taken too much time to complete this. I will let @zachlatta take initiative on reading it himself.
