### ISSUE TITLE
Week of 10.19.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#232]
### Curriculum

- [ ] ~~Ship MVP of "How to build workshops" (@MaxWofford, hackedu/meta#221)~~

### Community

- [x] Create script to quantify hackEDU Leaders group activity #258 (@hellyeah,
  hackedu/hackedu#258)
- [ ] Get at least 3 clubs submitting feedback to Packrat (@hellyeah,
  hackedu/hackedu#373)

### Technical

- [ ] Packrat authentication flow should be reworked (@MaxWofford,
  hackedu/packrat#76)
- [ ] Packrat attendance should be visible on feedback forms (@MaxWofford,
  hackedu/packrat#75)
- [x] Collect missing phone numbers (@zachlatta, hackedu/packrat#77)
- [x] IRC <> Slack integration (@zachlatta, hackedu/meta#209)
- [ ] Markcop refactor (@MaxWofford, hackedu/markcop#13)
- [ ] Extra Markcop checks (ex. double newlines) (@MaxWofford,
  hackedu/markcop#11, hackedu/markcop#12, hackedu/markcop#14,
  hackedu/markcop#15)

### Meta

- [x] Add new rows for clubs meeting this week and remove cancelled meetings
  from https://clubs.hackedu.us (@jonleung, hackedu/meta#223)
- [x] Check in with club leaders and add their planned curriculum for this week
  (10.19) to the Meetings sheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#224)
- [x] Merge https://github.com/hackedu/hackedu/issues/267 (@jonleung,
  hackedu/hackedu#267)
- [x] Reschedule semester planning session to Tuesday (~~10/20~~ 10/27) and book room
  (@zachlatta, hackedu/meta#229)
- [x] Add Who's Leading Standups in the title of the standup event (@zachlatta,
  hackedu/meta#230)
- [x] Make sure https://github.com/hackedu/hackedu/issues/364 gets done
  (@zachlatta)
- [ ] Everyone reads
  http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf
  (@jonleung, hackedu/meta#228)
- [ ] Follow-up Logan foundation report (@zachlatta, hackedu/meta#222)
- [ ] Rename case study folders (@zachlatta, hackedu/hackedu#379)
- [ ] ~~Update HackingEDU spreadsheet to make it private (@jonleung)~~
    - _Cancelled because many people have already been shared the link and
      making the sheet private might remove access for important people_

/cc @hellyeah @jonleung @MaxWofford

-------------------------------------------------------------------------------

EDIT by @MaxWofford: Cancelled hackedu/meta#221

**Comment by jonleung** [comment]
@zachlatta I removed

> - [ ] ~~Update HackingEDU spreadsheet to make it private (@jonleung)~~
>    - _Cancelled because many people have already been shared the link and
      making the sheet private might remove access for important people_

**Comment by jonleung** [comment]
^ @zachlatta, oops I didn't mean to do the above, I added it back in.

**Comment by zachlatta** [comment]
Closing because week is over. This week's issue is in #250.
