### ISSUE TITLE
Week of 10.26.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#250]
### Community

- [x] Each member of the team takes three clubs and works with them to get
  attendance, feedback, and, case studies for this week and next (@zachlatta,
  hackedu/meta#244)
- [ ] Get every cohort 2 labs leader to message Slack (@hellyeah,
  hackedu/hackedu#419)

### Curriculum

- [ ] Create workshop (@jonleung, hackedu/hackedu#339)
- [ ] Backlog
  - [ ] Prototype curriculum / general portal (@jonleung, hackedu/hackedu#421)

### Technical

- [x] Dockerize Markcop (@zachlatta, hackedu/markcop#19)
- [ ] Refactor Markcop (@MaxWofford, hackedu/markcop#13)

### Meta

- [x] Logan grant proposal (@zachlatta, hackedu/meta#231)
- [x] Cancel team lunch (@zachlatta)
- [ ] Talk to Soylent about in-kind donation (@hellyeah, hackedu/meta#236)
- [ ] Adopt code of conduct (@hellyeah, hackedu/meta#117)
- [x] Clean up cancelled club meetings in meetings sheet and create new rows
  (@jonleung, hackedu/meta#241)
- [ ] Check in with club leaders and add their planned curriculum for this week
  (10.26) to the Meetings sheet in https://clubs.hackedu.us (@jonleung,
  hackedu/meta#242)
- [ ] Everyone works from a fork this week (@zachlatta, hackedu/meta#249)
- [ ] Everyone reads
  http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf
  (@jonleung, hackedu/meta#228)
- [ ] Add license to hackedu/hackedu (@zachlatta, hackedu/hackedu#260)
- [x] 2 space indent in styleguide (@zachlatta, hackedu/meta#152)
- [ ] Add license to hackedu/hack-camp (@zachlatta, hackedu/hack-camp#529)
- [ ] Add missing clubs in the Airtable to https://clubs.hackedu.us (@zachlatta,
  hackedu/hackedu#264)
- [ ] Backlog
  - [ ] ~~Synthesize club leader feedback (@jonleung, hackedu/meta#212)~~

/cc @hellyeah @jonleung @MaxWofford

**Comment by hellyeah** [comment]
@zachlatta moved Code of Conduct to next week. Will require way more reading than I allocated time for.

**Comment by zachlatta** [comment]
Next week's issue is in #270. Closing this since the week is over.
