### ISSUE TITLE
Week of 11.02.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#270]
### Community

- [ ] 4 paired calls with 8 club leaders (@hellyeah, hackedu/meta#263)
- [x] Grow number of messages sent by non-core Slack members by 10% by next
  Monday (@hellyeah, hackedu/meta#264)

### Metrics

- [ ] Get attendance count from all Labs clubs (@MaxWofford)
  - [ ] @hellyeah (hackedu/meta#265)
    - [ ] Armijo High School
    - [ ] Cherry Hill High School
    - [ ] Project Cipher
    - [ ] Lowell High School
    - [ ] Ravenwood High School
    - [ ] Elizabeth High School
  - [ ] @MaxWofford (hackedu/meta#268)
    - [x] USC Hybrid High School
    - [x] San Leandro High School
    - [ ] College Park High School
    - [x] South Brunswick High School
    - [x] Columbia Secondary School
    - [x] Glenaeon Rudolf Steiner School
- [x] Put together system to aggregate attendance data and put the data from
  last week into it (@MaxWofford, hackedu/meta#266)

### Curriculum

- [ ] Ship Maze workshop (@jonleung, hackedu/hackedu#339)
- [x] MVP of playbook portal (just a Markdown file) (@jonleung,
  hackedu/hackedu#421)
- [ ] Talk with club leaders about their planned curriculum and add it to
  https://clubs.hackedu.us in the Meetings sheet (~~@jonleung~~@maxwofford, hackedu/meta#262)

**Comment by MaxWofford** [comment]
@zachlatta I motion that @jonleung's first issue is to get well.

**Comment by jonleung** [comment]
Assigning this issue to you @zachlatta because I know that you said you needed to do some work on this before we can close it.

**Comment by zachlatta** [comment]
Closing because the week is over. Next week's issue is in #293.
