### ISSUE TITLE
Plan Weekly Call

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#304]
**Task Description**

_Note that these are Jonathan's personal notes:_

**Before the call on Friday**

- [ ] Experiment with using [Unhangouts](unhangout.media.mit.edu) (the call currently has 10 people confirmed (which is the maximum number of people you can fit in a hangouts). Unhangouts supports a lot more people.
- [ ] Decide on virtual meeting room for the weekly call
- [ ] Create an agenda for the weekly call
  - [ ] Talk to club leaders about ideas
- [ ] Create Calendar event to the weekly call and invite everyone
- [ ] Make an announcement to labs leaders in #announcements about it
- [ ] PM everyone asking them if they can make the call if they didn't fill out the doodle

**After the call on Friday**

- [ ] PM everyone to ask them if this works for them for future
- [ ] Create Calendar Event for future Times

---

**Notes From Before**

_From @jonleung on November 3, 2015 6:59_

Now that we've merged labs and are also doing pairing, @hellyeah, we should think about what the weekly call will look like. Do we still want them? If so, how might that work?

_Copied from original issue: hackedu/hackedu#457_

**Comment by zachlatta** [comment]
When did we merge the Labs cohorts?

**Comment by zachlatta** [comment]
_From @jonleung on November 3, 2015 7:36_

Just now.

**Comment by zachlatta** [comment]
_From @MaxWofford on November 5, 2015 23:9_

@jonleung Should this have a `discussion` label?

**Comment by zachlatta** [comment]
Thoughts on planning to have a weekly call?

**Comment by paked** [comment]
This kind of needs to be resolved soon... Cause a *lot* of confusion last Friday PST.

**Comment by zachlatta** [comment]
@jonleung can you take point on getting this resolved?

**Comment by jonleung** [comment]
@zachlatta yes!

**Comment by hellyeah** [comment]
Weekly call sounds like a good idea but we'll likely have to take a tradeoff of who can make it.

**Comment by JevinSidhu** [comment]
A weekend works better for me -- can we nail a time soon? I believe Saturdays only work for @paked in the case of weekends. 

I'm in EST, so three hours ahead. Anytime between 4:30pm-8:00pm PST works good for me!

**Comment by hellyeah** [comment]
It's unlikely there's a time that works for everyone -- @jevinsidhu did you ever send out that Doodle?

**Comment by jonleung** [comment]
@hellyeah, @JevinSidhu created [the Doodle](http://doodle.com/poll/n4rbsqvmgc6e7g9i)! Thanks for that!

**Comment by JevinSidhu** [comment]
@hellyeah, the date that worked best for the people who filled out the Doodle is Friday, November 20th @ 7pm PST

**Comment by zachlatta** [comment]
@jonleung I know you said you'd send out the calendar invite. How's that going?

**Comment by paked** [comment]
Done. According to my inbox xD

**Comment by zachlatta** [comment]
Schweet. Closing!
